print ("##############################")
print ("#                            #")
print ("#    Muhammad Alfi Gunawan   #")
print ("#        2410817110009       #")
print ("#                            #")
print ("##############################")
